### ISSUE TITLE
Is nil(State) a typo?

### ISSUE THREAD

**Issue by liumingc** [thautwarm/MLStyle.jl#29]
https://github.com/thautwarm/MLStyle.jl/blob/5344f6390fcce9c7852da8cc5001c9ce9191e0da/src/toolz.jl#L44

**Comment by thautwarm** [comment]
Yes, thank you!

I used to use DataStructure.jl that exports such a constructor. However, a problem about linked lists with heterogeneous elements just occurred(check https://github.com/JuliaCollections/DataStructures.jl/pull/470), and since that I use a custom implementation. It seems that some deprecated codes haven't been removed properly.

Currently I'm in an ill and may not be able to fix this typo at once. If possible, could you please help me with this, also it's okay to refuse :-)
