### ISSUE TITLE
MLStyle as a generic search and replace tool ?

### ISSUE THREAD

**Issue by jonathanBieler** [thautwarm/MLStyle.jl#81]
I've been playing with the idea to make an AST aware search and replace for my refactoring package using MLStyle but I'm getting stuck. 

What I want to do is that the user can specify a search => replace pattern, e.g. 

```julia 
sin($x) => cos($x + 1)
```

And then I would go over the whole AST of the file and replace each expression matching `sin($x)` with `cos($x + 1)`.

For simple expressions a simple match does the job :

```julia
@match $ex begin
    $search => $replace
end
```

But then I don't know how to apply it recursively to the whole tree. Handling the inputs (e.g. `sin($x)`) is also a bit difficult.

My question is, do you think doing something like this is possible using MLStyle ? If so how would you go about it ?

Thanks.

**Comment by Roger-luo** [comment]
Hi @jonathanBieler , are you working on something like a symbolic engine? I think we discussed somewhere else (with @thautwarm ), so I believe for symbolic computing (or say just AST search and replace), we still need a more domain-specific pattern match instead of a generic one (like what MLStyle has here). You might want to customize some behavior such as detecting associative and communitive properties. 

I think @HarrisonGrodin implemented a more specific package [Rewrite](https://github.com/HarrisonGrodin/Rewrite.jl) for this purpose, you might want to check as well. 

Regarding to your question how to apply it recursively to the tree, I think you will need to write something like


```jl
function do_somthing(ex::Expr)
      @match $ex begin
                sin($x) => cos($x + 1)
                _ => map(do_something, ex.args)
       end
end
```

but this might currently not be very convenient for manipulating expressions since we cannot sperate rules from match algorithm.

**Comment by thautwarm** [comment]
Besides of @Roger-luo 's proposal, maybe the following way suffices?
```julia
julia> subst(a) = MLStyle.@match a begin
           :(sin($x)) => :(cos($x + 1))
           _       => a
       end
julia>  MacroTools.prewalk(subst,
         :(sin(x + sin(x))))

:(cos((x + cos(x + 1)) + 1))
```

**Comment by jonathanBieler** [comment]
I'm not doing a symbolic engine no, I rather want to provide tools for editors/IDE's (I already
have method extraction kinda working). It looks like this AST-aware replacement would be a bit nicer than using regex, although I'm not sure how useful it would actually be in practice.

This seems to do the job :

```julia
macro search_and_replace(ex, search, replace)
    ex = Expr(:quote, ex)
    search  = Expr(:quote, search)
    replace = Expr(:quote, replace)
    esc(quote
        MacroTools.prewalk(x -> MLStyle.@match x begin
            $search => $replace
            _ => x
        end
        , $ex)
    end)
end
```
