### ISSUE TITLE
Matching on types as values gives the wrong result

### ISSUE THREAD

**Issue by rdeits** [thautwarm/MLStyle.jl#91]
Here's a simple example:

```
julia> using MLStyle: @match

julia> T = Int
Int64

julia> @match T begin
         Float64 => println("float")
         Int => println("int")
       end
float
```

This prints `float` even though `T == Int` and `T != Float64`. 

Interestingly, I see the exact same error in https://github.com/kmsquire/Match.jl/issues/61 which is enough to make me start questioning my sanity and/or my assumptions about where I'm using the tools correctly.

**Comment by thautwarm** [comment]
Because as the documentation said, `Float64` here is just a capture pattern, it binds `T` to `Float64`. If you want to match the type, please use `::Float64`.

This is not an error as it's an expected behavior and should be already documented in MLStyle.jl or Match.jl.

The reason why a simple symbol is always used for binding names instead of referencing existing names is,  supporting both semantics will always make the code unreadable. 
**We must make the semantics of a symbol predictable for users.**

See 
- [Capture Patterns](https://thautwarm.github.io/MLStyle.jl/latest/syntax/pattern.html#capturing-patterns)

- [Type Patterns](https://thautwarm.github.io/MLStyle.jl/latest/syntax/pattern.html#type-patterns)


MLStyle did a lot to address the inconvenience caused by this design.

An exception is a pattern object `P` which satisfies `MLStyle.is_enum(P) === true`, in this case, a pattern `P` is equivalent to a pattern `P()`.

Another related thing is the [Reference Patterns](https://thautwarm.github.io/MLStyle.jl/latest/syntax/pattern.html#reference-patterns).

For your use case, if you want to use a pattern `Float64` as the pattern `::Float64`:

```julia
MLStyle.is_enum(::Type{Float64}) == true
function pattern_uncall(::Type{Float64}, self::Function, tparams, targs, args)
    isempty(tparams) && isempty(targs) && isempty(args) || error("invalid pattern Float64")
    self(:(::$Float64))
end
```

**Comment by rdeits** [comment]
I see--so the semantics are that the left-hand-side of each pair is a variable binding, unless that left-hand-side is a literal number or string? I was confused by the first example here: https://thautwarm.github.io/MLStyle.jl/latest/syntax/pattern.html#literal-patterns and assumed that I could substitute a value for the literal in that example. 

Thank you for taking the time to explain this!
